version: "3.8"

services:
  db:
    image: postgres:12
    container_name: postgres-db
    env_file: ./backend/catalogo_arqueologico/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: ./backend
    container_name: django-backend
    env_file: ./backend/catalogo_arqueologico/.env
    volumes:
      - ./backend:/app
      - ./data:/app/data  # Mount the data directory
      - django_media:/app/media  # Use a named volume for media
    ports:
      - "8000:8000"
    depends_on:
      - db

  react:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
    command: npm start

volumes:
  postgres_data:
  django_media:  # Named volume for Django media files