# Generated by Django 4.2.13 on 2024-07-02 04:22

from django.db import migrations, models
import piezas.models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(blank=True, help_text='Enter unique identifier without dots or dashes', max_length=9, validators=[piezas.models.validateRut]),
        ),
    ]
