# Generated by Django 4.2.13 on 2024-06-03 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='id_culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='culture', to='piezas.culture'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='id_shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shape', to='piezas.shape'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='id_thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='piezas.thumbnail'),
        ),
    ]
