# Generated by Django 4.2.13 on 2024-06-27 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_artifact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='piezas.artifact'),
        ),
    ]
