# Generated by Django 4.2.13 on 2024-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_alter_customuser_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactrequester',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cultureids',
            name='artifactid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultureids',
            name='culture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shapeids',
            name='artifactid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shapeids',
            name='shape',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tagsids',
            name='artifactid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tagsids',
            name='tag',
            field=models.IntegerField(),
        ),
    ]
