# Generated by Django 4.2.13 on 2024-07-01 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_alter_artifact_id_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactRequester',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_registered', models.BooleanField(default=True)),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_requester', to='piezas.artifact')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_requester', to='piezas.institution')),
            ],
        ),
    ]
