# Generated by Django 4.2.13 on 2024-05-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_alter_media_path_alter_metadata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='piece_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='piezas.piezaarq'),
        ),
    ]
