# Generated by Django 4.2.13 on 2024-07-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0003_artifactrequester_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactrequester',
            name='comments',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
