# Generated by Django 4.2.13 on 2024-05-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0003_media_piece_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='piece_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='piezas.piezaarq'),
        ),
    ]
