# Generated by Django 4.2.13 on 2024-05-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0004_alter_media_piece_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='piece_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='piezas.piezaarq'),
        ),
    ]
