# Generated by Django 4.2.13 on 2024-05-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0006_remove_media_piece_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='piece_id',
        ),
    ]
