# Generated by Django 4.2.13 on 2024-05-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0007_remove_metadata_piece_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureIds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('artifactid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShapeIds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('artifactid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TagsIds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('artifactid', models.IntegerField()),
            ],
        ),
    ]
