# Generated by Django 4.2.13 on 2024-05-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0008_cultureids_shapeids_tagsids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultureids',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shapeids',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tagsids',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
