# Generated by Django 4.2.13 on 2024-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0009_alter_cultureids_id_alter_shapeids_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultureids',
            name='culture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shapeids',
            name='shape',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tagsids',
            name='tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cultureids',
            name='artifactid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cultureids',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shapeids',
            name='artifactid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shapeids',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tagsids',
            name='artifactid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tagsids',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
