# Generated by Django 4.2.13 on 2024-05-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0010_cultureids_culture_shapeids_shape_tagsids_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('path', models.ImageField(unique=True, upload_to='images/')),
                ('id_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='piezas.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('texture', models.ImageField(unique=True, upload_to='textures/')),
                ('object', models.FileField(unique=True, upload_to='objects/')),
                ('material', models.FileField(unique=True, upload_to='materials/')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('path', models.ImageField(unique=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.RemoveField(
            model_name='piezaarq',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='piezaarq',
            name='form',
        ),
        migrations.RemoveField(
            model_name='piezaarq',
            name='model',
        ),
        migrations.RemoveField(
            model_name='piezaarq',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='piezaarq',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
        migrations.DeleteModel(
            name='PiezaArq',
        ),
        migrations.AddField(
            model_name='artifact',
            name='id_culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture', to='piezas.culture'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='id_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model3d', to='piezas.model'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='id_shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shape', to='piezas.shape'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='id_tags',
            field=models.ManyToManyField(to='piezas.tag'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='id_thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='piezas.thumbnail'),
        ),
    ]
