# Generated by Django 4.2.13 on 2024-05-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0011_artifact_culture_image_model_shape_tag_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='id_model',
        ),
    ]
