# Generated by Django 4.2.13 on 2024-05-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0012_remove_artifact_id_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='id_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='model3d', to='piezas.model'),
        ),
    ]
